kind = "api"
previewPath = "/"
title = "ChatGPT Account Checker"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "Checker"
paths = ["/"]

[services.env]
PORT = "8000"

[services.development]
run = "cd /home/runner/workspace/checker && python run.py"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/node-api"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"
